esphome:
  name: s3
  friendly_name: s3
  platformio_options:
    board_build.flash_mode: dio

esp32:
  board: lolin_s3
  variant: esp32s3
  framework:
    type: esp-idf

logger:
  level: DEBUG

#api:
#  encryption:
#    key: !secret api_key

#ota:
#  - platform: esphome
#    password: !secret ota_password

wifi:
  ssid: !secret personal_hotspot_ssid
  password: !secret personal_hotspot_password

mqtt:
  broker: xxxxxxxxxxxxxx-ats.iot.us-east-1.amazonaws.com
  port: 8883
  client_id: YourThingName # maybe not necessary
  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    -----END CERTIFICATE-----
  client_certificate: |
    -----BEGIN CERTIFICATE-----
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    -----END CERTIFICATE-----
  client_certificate_key: |
    -----BEGIN RSA PRIVATE KEY-----
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    ................................................................
    -----END RSA PRIVATE KEY-----
  discover_ip: False
  discovery: False
  discovery_retain: False
  topic_prefix: null
  log_topic: null
  birth_message: 
    topic:
    payload:
  will_message: 
    topic:
    payload:
  
esp32_ble_tracker:

ble_client:
  - mac_address: XX:XX:XX:XX:XX:XX
    id: veepeak

external_components:
  - source: my_components

obd2_ble_mqtt:
  id: mycar
  service_uuid: "0xFFF0"
  characteristic_uuid:
    write: "0xFFF2"
    read: "0xFFF1"
    notify: "0xFFF1"
  init_commands: "ATZ ATE0 ATL0 ATS0 ATH1 ATSP0 ATDPN 0100"
  topic: "$aws/things/YourThingName/shadow/name/NamedShadowName/update"

sensor:
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "ATRV"
    mode: "AT"
    pid: "RV"
    unit_of_measurement: "V"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Engine Coolant Temperature"
    can_id: "7E9"
    mode: "01"
    pid: "05"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "STFT"
    can_id: "7E8"
    mode: "01"
    pid: "06"
    unit_of_measurement: "%"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "LTFT"
    can_id: "7E8"
    mode: "01"
    pid: "07"
    unit_of_measurement: "%"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Fuel Tank Level Input"
    can_id: "7E8"
    mode: "01"
    pid: "2F"
    unit_of_measurement: "%"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Absolute Barometric Pressure"
    can_id: "7E8"
    mode: "01"
    pid: "33"
    unit_of_measurement: "kPa"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Control Module Voltage"
    can_id: "7E8"
    mode: "01"
    pid: "42"
    unit_of_measurement: "V"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Ambient Air Temperature"
    can_id: "7E8"
    mode: "01"
    pid: "46"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Engine Oil Temperature"
    can_id: "7E8"
    mode: "01"
    pid: "5C"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "ECT Sensor 1 Temperature"
    can_id: "7E8"
    mode: "01"
    pid: "67"
    bits: "B"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "ECT Sensor 2 Temperature"
    can_id: "7E8"
    mode: "01"
    pid: "67"
    bits: "C"
    unit_of_measurement: "°C"
    accuracy_decimals: 1

text_sensor:
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Fuel System Status"
    can_id: "7E8"
    mode: "01"
    pid: "03"
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Stored DTC"
    can_id: "7E8"
    mode: "03"
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Pending DTC"
    can_id: "7E8"
    mode: "07"
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Permanent DTC"
    can_id: "7E8"
    mode: "0A"

binary_sensor:
  - platform: obd2_ble_mqtt
    obd2_ble_mqtt_id: mycar
    name: "Stored P0010"
    mode: "03"
    code: "P0010"

